package com.sapi.dep.simapi

import android.app.Activity
import android.app.AlertDialog
import android.content.Context
import android.content.SharedPreferences
import android.content.res.Resources
import android.graphics.Bitmap
import android.graphics.BitmapFactory
import android.graphics.Color
import android.graphics.Typeface
import android.os.Bundle
import android.os.Handler
import android.support.constraint.ConstraintLayout
import android.support.constraint.ConstraintSet
import android.support.v4.app.Fragment
import android.support.v4.app.FragmentManager
import android.support.v4.app.FragmentTransaction
import android.support.v4.content.ContextCompat
import android.support.v7.widget.CardView
import android.text.Html
import android.transition.Fade
import android.transition.Slide
import android.transition.TransitionSet
import android.util.Base64
import android.util.DisplayMetrics
import android.util.Log
import android.view.Gravity
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import android.widget.*
import com.android.volley.DefaultRetryPolicy
import com.android.volley.Request
import com.android.volley.Response
import com.android.volley.Response.Listener
import com.android.volley.toolbox.JsonObjectRequest
import com.android.volley.toolbox.Volley
import com.bumptech.glide.Glide
import com.bumptech.glide.request.RequestOptions
import com.muddzdev.styleabletoastlibrary.StyleableToast
import com.weiwangcn.betterspinner.library.material.MaterialBetterSpinner
import kotlinx.android.synthetic.main.anamesa.view.*
import kotlinx.android.synthetic.main.app_bar_navigation.*
import kotlinx.android.synthetic.main.card_filter1.view.*
import kotlinx.android.synthetic.main.card_filter2.view.*
import kotlinx.android.synthetic.main.inseminasi.view.*
import kotlinx.android.synthetic.main.kebuntingan.view.*
import kotlinx.android.synthetic.main.peternak.view.*
import kotlinx.android.synthetic.main.sample.view.*
import kotlinx.android.synthetic.main.ternak.view.*
import kotlinx.android.synthetic.main.vaksinasi.view.*
import org.json.JSONArray
import org.json.JSONObject
import java.io.ByteArrayOutputStream
import java.io.InputStream
import jav